language: node_js
node_js:
  - 'node'

cache: yarn

addons:
  srcclr: true
  code_climate: true

after_success:
  - yarn global add codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.ingo